### ISSUE TITLE
Jest: TypeError: Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by imranweb** [react-native-async-storage/async-storage#399]
## Current behavior

While running the jest test runner "yarn test" I am getting this error
**node_modules/redux-persist/lib/createPersistoid.js:98
    writePromise = storage.setItem(storageKey, serialize(stagedState)).catch(onWriteFail);
TypeError: Cannot read property 'catch' of undefined**
## Environment

- **Async Storage version**: 
- **React-Native version**: 
- **Platform tested**: 
- **Logs/Error that are relevant**:

**Comment by Krizzu** [comment]
Can you provide some repro steps?

**Comment by tido64** [comment]
Closed due to inactivity.

**Comment by phelipetls** [comment]
Unwrapping `jest.fn` from the `setItem` method in `"@react-native-async-storage/async-storage/jest/async-storage-mock"` seems to resolve the issue, but it's not ideal.

I'm not sure why this happens, this [Stack Overflow answer](https://stackoverflow.com/questions/66984091/create-react-app-changes-behaviour-of-jest-fn-when-mocking-async-function) describes a similar problem.

If that's what's happening, then the implementation function passed to jest.fn is being reset by jest. But I doubt because passing `resetMocks: false` to the Jest configuration does not fix the issue.

I got my tests to pass by not using `jest.fn` in the `setItem` method.
