### ISSUE TITLE
Expo managed workflow usage?

### ISSUE THREAD

**Issue by Joshandrews43** [react-native-async-storage/async-storage#513]
How do you use this library using the managed workflow? All the docs show `npx pod install` as a requirement, and I really don't want to eject.

**Comment by samtsai** [comment]
Any resolution or were there actually no additional steps?

**Comment by Krizzu** [comment]
It's simple as that - just install the package and you're done. Expo is supported since version v1.11.0 (using AsyncStorage from React Native itself).

**Comment by Joshandrews43** [comment]
From the documentation under troubleshooting: 

```
If you have an Expo app, AsyncStorage will not work unless you eject the app. After ejecting the app, you may have to manually link depending on whether you chose to use Expo SDK.
```

I still cannot get this to work.

**Comment by Krizzu** [comment]
@Joshandrews43 Oh, this should actually be removed - it's no longer the case for version mentioned above.

**Comment by lucascampelo** [comment]
There are any progress with this issue ? I'm having the sabe trouble with `expo` and `@react-native-async-storage/async-storage`.

**Comment by tido64** [comment]
@lucascampelo: What is the issue that you're seeing? Have you tried looking in Expo's forums? For instance, this seems to be something that people hit all the time that have a solution: https://forums.expo.io/t/expo-40-rn-asyncstorage-nativemodule-asyncstorage-is-null/46757/4. Otherwise, please file a new issue with details and a minimal repro so we can better help you.

As for this issue: There is nothing to fix here as the problem is not on our end.
