### ISSUE TITLE
Can hackers add stuff to your app's asynchronous storage?

### ISSUE THREAD

**Issue by avlonder** [react-native-async-storage/async-storage#584]
## You want to:  
Ask a question

## Details:
I know it's not a good idea to store sensitive data with AsyncStorage because others can READ it, but are others also able to WRITE stuff to your app's storage?

**Comment by Krizzu** [comment]
A lot has been changed since we extracted Async Storage from RN core. On Android, SQLite is used, which is stored inside your app directory, where no other apps has access to (unless the device is rooted). On iOS, we moved the location of where the storage file is kept - now it's Application Support. From Apple docs:

```
In general, this directory includes files that the app uses to run but that should remain hidden from the user. This directory can also include data files, configuration files, templates and modified versions of resources loaded from the app bundle.
 ``` 
Async Storage has no extra layer of security, but the access from other apps to the db file is protected by OS, so others cannot read/write to it.
