### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Poojamok** [react-native-async-storage/async-storage#734]
i am store data in async-storage using set method, it store successfully but when i am click on next page for getting data using get method it doesnot show anything after referesh page it show me why this happen?

**Comment by Krizzu** [comment]
Can you provide the code you use (or repo), so we have a look? Also, please do not remove template from issue, as info about your environment would be helpful identifying the problem.

**Comment by Poojamok** [comment]
System info:
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
    Memory: 935.81 MB / 7.64 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.18.1 - /tmp/yarn--1646202246453-0.15090997048887567/node
    Yarn: 1.22.17 - /tmp/yarn--1646202246453-0.15090997048887567/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.2 => 0.67.2 
  npmGlobalPackages:
    *react-native*: Not Found
Done in 2.28s.

**Comment by krizzu** [comment]
Issue is not related to AsyncStorage, but to your component.
It seems like you're using class component. In there you declare `data` method which would call AsyncStorage. But the problem is that your `data` is not bound to the instance of your component. You have to bind method to your component, otherwise the context is lost when React calls it.

The fix would be to change:
```diff
-data(){
+data = () => {
     this.fetchCats().then((wish)=>{
      if (wish !== null) {
        // We have data!!
        const wishproduct = JSON.parse(wish)
        this.setState({wishItems:wishproduct}); 
        this.setState({ refreshing: false });
      }
    })
```

As a side note, I'd suggest to read up why you have to do this. And later on, read about functional components with hooks in React (preferred way of writing components).

**Comment by Poojamok** [comment]
Thank you for your reply i have solve using functional components with
hooks.
