### ISSUE TITLE
 > Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac FAILED  Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### ISSUE THREAD

**Issue by alihaxan020** [react-native-async-storage/async-storage#770]
### What happened?

I am facing this issue please
> Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.

### Version

1.15.17

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 5.99 GB / 15.87 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version     2021.1.0.0 AI-211.7628.21.2111.8139111
    Visual Studio: Not Found
  Languages:
    Java: 15.0.2 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Task :react-native-async-storage_async-storage:compileDebugJavaWithJavac FAILED

**Comment by krizzu** [comment]
Can you post the full gradle error? I saw this `Deprecated Gradle features` being only a warning, while there might be other issue

**Comment by alihaxan020** [comment]
Thank you @krizzu. I have solved the issue, I have deleted the node modules, and then install it again,

**Comment by Mehul1437** [comment]
I also got the same issue. Any update about this bug ??

**Comment by daniimd** [comment]
same here

**Comment by ZohaibAhmad001** [comment]
Samer here

**Comment by tido64** [comment]
Hi folks,

`Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0` is never a cause for build failure. It is only a warning. If your build is failing, please file a new issue, post the FULL build log, and create a minimal reproducible case so others can debug your issue. There are no single issue that leads to build failure. We need more information in order to help you.

Before you file a new issue, please also make sure that you're not being hit by this: https://github.com/facebook/react-native/issues/35210
