### ISSUE TITLE
More like a discussion: Is there a way to persist data across app uninstall / install?

### ISSUE THREAD

**Issue by vlimag** [react-native-async-storage/async-storage#796]
### What happened?

I need to persist data across app installations in order to trigger specific events only for first opens.

Therefore, if a user reinstall the app, this event should not trigger.

### Version

1.15.15

### What platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: macOS 12.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 94.90 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.02.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 25, 26, 27, 28, 29, 30, 31, 32
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2, 33.0.0
      System Images: android-25 | Google APIs Intel x86 Atom, android-29 | Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom, android-31 | Intel x86 Atom_64, android-31 | Google Play Intel x86 Atom_64, android-S | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.3.1/13E500a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.13 - /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

- Install app
- Set data to be persisted
- Remove app
- Install app
- get data

**Comment by tewedaj** [comment]
i think i can add this feature for android.. will see what i can do when i get home

**Comment by tewedaj** [comment]
looked in to this today, it's not actually possible, since we need a root access to copy file from the `/data/data/packageName/AsyncStorage` folder so we can not copy it programmatic, the next best solution i have for you is using shared preferences and since this package is SQLite based, you should use **react-native-shared-preferences** instead and edit the manifest file by adding `android:allowBackup=” true”` but that has some known vulnerabilities so you should read on that first, i was hopping this was gonna be my first contribution to an opensource project but i realized it doesn't work after writing the code lol
