### ISSUE TITLE
incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by Kenjy62** [react-native-async-storage/async-storage#861]
### What happened?

I have an error on a new project when i run react-native run-android

`> Task :react-native-async-storage_async-storage:generateDebugRFile FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.`

### Version

Latest

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
All latest versions
```

### Steps to Reproduce

Run npx react-native run-android after npm install @react-native-async-storage/async-storage

**Comment by SaraChicaD** [comment]
Also having this issue. Any updates?

**Comment by aditya-upadhye** [comment]
@Kenjy62 and @SaraChicaD 

I am also facing the same issue. Are there any updates on how to fix it?

**Comment by bipinyadav3175** [comment]
I am also getting the same issue. Last time I built this project, it was working fine. But today suddenly it gave this error.

I have tried:

- running ./gradlew clean and rebuilding the project
- Reinstalling async storage

But nothing seems to work

When I tried to build the project after removing the async storage package, It gave the same error with react-native-gesture-handler

Like this:
`> Task :react-native-gesture-handler:generateDebugRFile FAILED Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.`

I don't know this error is casued due to async storage or something else
I hope this gets solved as soon as possible

**Comment by Kenjy62** [comment]
I tried many solutions, none worked. Strangely after restarting my machine, the problem disappeared. I don't know how this is possible..

**Comment by aditya-upadhye** [comment]
> I tried many solutions, none worked. Strangely after restarting my machine, the problem disappeared. I don't know how this is possible..

Are you sure you didn't do anything else but just restarted your system?
Coz the problem still persists for me.

**Comment by Kenjy62** [comment]
@aditya-upadhye After trying several solutions that didn't work, yes I just restarted, it's really strange.

**Comment by aditya-upadhye** [comment]
> @aditya-upadhye After trying several solutions that didn't work, yes I just restarted, it's really strange.

Luckily it works for you. It doesn't work for me. I tried restarting and serveral solutions from StackOverFlow and many more sources. The main problem I am having is that I am having a project review just a day later and my app is not gonna work :(

**Comment by bipinyadav3175** [comment]
> For all of you hitting Android build issues, please have a look at this issue first: [facebook/react-native#35210](https://github.com/facebook/react-native/issues/35210)
> 
> If your issue is related to Gradle 8.0 deprecation warning, please provide more logs so we can figure out what it's complaining about. If your build is failing because of this, you probably enabled treating [warnings as errors](https://developer.android.com/reference/tools/gradle-api/7.3/com/android/build/api/dsl/Lint). This really shouldn't fail your build.

This worked for me and should work for everyone else too.

**Something about the issue:**

- The root cause of the issue is react-native 's new distribution strategy
- Most of the react native developers are affected due to this
- People at react native are helping to solve this issue: facebook/react-native#35210

**Thanks @tido64 for this important information**

**Comment by aditya-upadhye** [comment]
@Kenjy62 @SaraChicaD @tido64 @bipinyadav3175 
Thanking all you people. Because of your active replies and updates, I am now able to run my app without any errors.

**Comment by SaraChicaD** [comment]
@aditya-upadhye - how did you fix it?

**Comment by aditya-upadhye** [comment]
> @aditya-upadhye - how did you fix it?

As mentioned by @tido64 and @bipinyadav3175,
I checked out this: https://github.com/facebook/react-native/issues/35210
The patch (fix) for the same was released and all you had to do was update your react-native to the versions specified. 
My project was using React Native v0.67.2. I decided to move on with v0.67.5 which had the patch. In my project folder, I updated the same in my `package.json` and `package-lock.json` files. Then I deleted node modules and by opening terminal in the project directory, I typed `npm install` and hence the updated version of React Native was installed. 

Finally, using `npx react-native run-android` worked for me.

**Comment by SaraChicaD** [comment]
@aditya-upadhye -- thanks for sharing! still working on getting mine to work, i did get past the error for this library though!

**Comment by krizzu** [comment]
As everyone has mentioned already, please refer to https://github.com/facebook/react-native/issues/35210 to failing builds, due to the recent publication of RN to Maven Central.

Please reopen if your issue is something else

**Comment by Franco832-boot** [comment]
Hi! I have a problem with install the patch to avoid gradle error Gradle 8.0 and it keeps crashing. Using the android studio simulator it works but at compile time it fails.
I would like to know where the problem is. I install React native 0.67.5
From already thank you very much
![OZ9a1](https://user-images.githubusercontent.com/116725532/209863534-f5f6a51f-0557-4482-a561-7c67760f68b8.png)

**Comment by hamzailyas237** [comment]
I faced the same issue i.e
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
I tried many solutions but none of them worked. In the end, I see that my phone's wifi is off.
Make sure that both connected devices have an internet connection.

**Comment by sri-karthick-k** [comment]
Have any of you found a solution. And where do I find gradlew on a react-native project?

**Comment by U-M-97** [comment]
In my case emulator is hanging and causing issues 
I just end task qemu emulator from task manager and build again fix the issue
